### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MussaCharles** [Lugriz/pdfmake-font-generator#2] opened 2020-02-15 08:36 UTC
I successfully generated custom fonts however when I try to use custom generated fonts on react project, I get this error right after trying to import the fonts file: -
```ruby
Failed to compile.
./src/fonts/custom-fonts.js
RangeError: Maximum call stack size exceeded
Occurred while linting ~/src/fonts/custom-fonts.js:3
    at String.match (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.map (<anonymous>)
```
Seems like there is a retain circle somewhere on the generated fonts source. 
Any thoughts on this?

**Comment by Lugriz** [comment] 2020-02-22 05:44
Hi @MussaCharles 

The generated fonts is just an object, I don't think the problem is in the generated file. Can you provide some extra information about your code implementation? for example: where you have the fonts you want to generate (directories structure), how you are imported the generated fonts.

**Comment by MussaCharles** [comment] 2020-02-22 11:42
Hi @Lugriz 
Thanks for the great tool. I successfully manage to use  the fonts I generated using this tool on the backend side, so I think it's not an issue with the generated fonts. 
However on React based front end project specifically the one made with  ```create-react-app```, comes with Linter which happens to trigger  that ```stack size exceeded``` error. 

This issue can be easily reproduced by create a new simple react project, put the font file in any of the folders and try to import it. I even tried the fonts generated in a similar way as own  ```pdf-make```  ```vfs_fonts.js``` , similar issue happens. So it is not an issue on this tool, I guess, because it works well on my backend side.

**Comment by Lugriz** [comment] 2020-03-03 22:42
Thanks for sharing it. I'll close this issue, because as you comment, it's not on this tool!

**Closed as completed by Lugriz** 2020-03-03 22:42 UTC
